name: Deploy MkDocs to GitHub Pages

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Permissions for deploying to gh-pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python (MkDocs requires Python)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Use a version compatible with MkDocs

      # Install dependencies (MkDocs and any plugins)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs  # Add other plugins like 'mkdocs-material' if needed

      # Build the MkDocs site
      - name: Build MkDocs site
        run: mkdocs build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site  # The folder MkDocs builds to (ignored in .gitignore)
